#商店的行数大小（1-4），一行7个物品
#商店是不会重复的
#如果设置的物品数量不大于商店大小则不会开张
ShopSize: 2
#收购商店的行数大小（1-4），一行7个物品
#商店是不会重复的
#如果设置的物品数量不大于商店大小则不会开张
BuyShopSize: 2

#出售商店头颅显示的玩家ID
PlayerSkull: 'Yuan_You'
#收购商店头颅显示的玩家ID
BuyPlayerSkull: 'Yuan_You'

#物品稀有分级
#请从小到大排序
#格式:'等级名称:刷新概率'
#概率都是单独计算，先从上再到下
Level:
  - '&c出口:1%'
  - '&f限定:1%'
  - '&e传说:2%'
  - '&5史诗:10%'
  - '&b精良:25%'
  - '&6丰收:33%'
  - '&a普通:50%'
  - '&f常驻:100%'

#每日刷新商店时，是否全服公告
DailyResetMessage: true
#每日收购刷新商店时，是否全服公告
BuyDailyResetMessage: true

#几点为新的一天的开始（自定义时间）
#小时
DailyHour: 20
#分钟
DailyMinute: 1


#添加最简食用例子
#例子：/ds add &c限定 100